# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8764d4d7e38c2e30293ed478df7ed613a08a18c96da9b69f921f433c3f0ff44da710cac1ff3d6ec79525bf31bd9a54b7834ebdbb1a944e458090d311acbdb5e0

test:
  secret_key_base: be1d2a4ecd0aea625e2a777625fc66b84df1f26788e725b6f6a0d848f72227551ac28c26e034e85afdeed6a4913553aeba5fc5dcab1a419c4766dffd803f3a5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
